name: "Points Bar"
description: "Generates a points/progress SVG bar"

inputs:
  points:
    description: "Points string separated with a / slash."
    required: true
  path:
    description: "File path to save the generated SVG to."
    required: true
  type:
    description: "Style of bar to generate; either bar or badge."
    default: "bar"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: check
  color: green
